---
extra: []
port: 8010
directory: '/'
output: '/output'
timeout: 10
logserver: false
loglevel: 'info'
options: []
filename: 'output/logs/tardigrade.log'
maxbytes: 0
count: 0
host: ''
url: ''
method: 'GET'
secure: false
credentials:
  username: ''
  password: ''

colors:
  pink: "\033[38;5;206m"
  black: "\033[1;30m"
  dark_blue: "\033[1;34m"
  dark_green: "\033[1;32m"
  dark_aqua: "\033[1;36m"
  dark_red: "\033[1;31m"
  dark_purple: "\033[1;35m"
  gold: "\033[1;33m"
  gray: "\033[1;37m"
  dark_gray: "\033[1;90m"
  blue: "\033[1;94m"
  green: "\033[1;92m"
  aqua: "\033[1;96m"
  red: "\033[1;91m"
  light_purple: "\033[1;95m"
  yellow: "\033[1;93m"
  white: "\033[1;97m"
  reset: "\033[0m"
  orange: "\033[38;5;208m"
mimetypes:
- key: ".jpeg"
  value: image/jpeg
- key: ".png"
  value: image/png
- key: ".gif"
  value: image/gif
- key: ".bmp"
  value: image/bmp
- key: ".svg"
  value: image/svg+xml
- key: ".pdf"
  value: application/pdf
- key: ".csv"
  value: text/csv
- key: ".txt"
  value: text/plain
- key: ".html"
  value: text/html
- key: ".css"
  value: text/css
- key: ".js"
  value: application/javascript
- key: ".json"
  value: application/json
- key: ".xml"
  value: application/xml
- key: ".zip"
  value: application/zip
- key: ".tar"
  value: application/x-tar
- key: ".rar"
  value: application/x-rar-compressed
- key: ".7z"
  value: application/x-7z-compressed
- key: ".rtf"
  value: application/x-sh
- key: ".ttf"
  value: font/ttf
- key: ".xhtml"
  value: application/xhtml+xml
- key: ".eml"
  value: message/rfc822
log_formats: #see https://docs.python.org/3/library/logging.html#logrecord-attributes
  default: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(reset)s[%(levelname)s] - %(funcName)s:Line:%(lineno)d : %(message)s"
  debug: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(dark_green)s[%(levelname)s] - %(gold)s:%(funcName)s%(reset)s Line:%(lineno)d : %(message)s"
  info: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(dark_blue)s[%(levelname)s] - %(gold)s:%(funcName)s%(reset)s Line:%(lineno)d : %(message)s"
  warning: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(orange)s[%(levelname)s] - %(gold)s:%(funcName)s%(reset)s Line:%(lineno)d : %(message)s"
  error: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(red)s[%(levelname)s] - %(gold)s:%(funcName)s%(reset)s Line:%(lineno)d : %(message)s"
  critical: "%(aqua)s%(title)s %(pink)s%(banner)s%(reset)s - %(purple)s%(asctime)s %(dark_red)s[%(levelname)s] - %(gold)s:%(funcName)s%(reset)s Line:%(lineno)d : %(message)s"
flag: true